### PR TITLE
jspm import support

### PR DESCRIPTION
**Pull request by fernandogmar**
Hi I hope you accept this pull request ;),

it adds support for importing less/css files from jspm packages just using the prefix `jspm://`

it is based on [lixiaoyan/less-plugin-jspm-import](https://github.com/lixiaoyan/less-plugin-jspm-import). I couldn't get it working using it directly. So I included the sources on this repository with the changes that I had to do ;)

Tests were changed enough... so with npm test you can check that everything works as before :D

Have fun!

### CODE REVIEW

**Comment by ffflabs** [comment]
Thanks. I will give it a look. Are the tests passing on your fork?

**Comment by fernandogmar** [comment]
Hi Felipe,

`npm test` works as smooth as silk ;). No idea what has failed on your atomated checks

**Comment by ffflabs** [comment]
@fernandogmar the issue with the test seems to be due to the fact that the package.json doesn't specify a default node engine.

PD: fuck, I downloaded from your branch and was able to push to it. I will try to solve conflicts this way, anyway

**Comment by ffflabs** [comment]
Ok, I'll convert your tests into new ones. So default @imports are tested along your jspm style imports.

**Review by ffflabs — APPROVED** [review]
It seems ok, after all the mess I left when I added your repo as remote @fernandogmar

**Comment by ffflabs** [comment]
@fernandogmar ok I blatantly fixed the conflicts myself on your fork. I'm sorry for that but it'll save us a lot of idle back and forth

**Comment by ffflabs** [comment]
@fernandogmar are you interested in becoming a contributor to this repo. I mean getting write privileges to create your own branches and pull requests without the need to fork. Also give me a hand dealing with issues.

**Comment by fernandogmar** [comment]
@amenadiel thanks!
being a contributor would be interesting ;)

**Comment by ffflabs** [comment]
@fernandogmar I had to move jspm-less-plugin to a separate folder, then run a build task to transpile its contents. I noticed that my tests (on another project) were failing due to phantomjs complaints about reserved word **class**.

I released it as v2.2.0

**Comment by fernandogmar** [comment]
awesome!

**Pull request merged**
